spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
    enabled: true
    suffix: .html
    mode: HTML
  security:
    user:
      name: admin
      password: admin

